module.exports = {
  "urlPath": '/stacks',
  "api_key": 'bltdaaa5dfadb94dc87',
  "stackHeaders": { api_key: 'bltdaaa5dfadb94dc87' },
  // update: [Function],
  // delete: [Function],
  // fetch: [Function],
  // contentType: [Function],
  // locale: [Function],
  // asset: [Function],
  // globalField: [Function],
  // environment: [Function],
  // deliveryToken: [Function],
  // users: [Function],
  // transferOwnership: [Function],
  // settings: [Function],
  // resetSettings: [Function],
  // addSettings: [Function],
  // share: [Function],
  // unShare: [Function],
  // role: [Function] 
}