import { Token, selectedOrganization, Stack, ContentType, Environment, Entry, Locale } from './interfaces';
export declare function chooseOrganization(client: any, displayMessage?: string, region?: string, orgUid?: string): Promise<selectedOrganization>;
export declare function chooseStack(client: any, organizationId: string, displayMessage?: string, region?: string): Promise<Stack>;
export declare function chooseContentType(stackApiKey: string, displayMessage?: string, region?: string): Promise<ContentType>;
export declare function chooseEntry(contentTypeUid: string, stackApiKey: string, displayMessage?: string, region?: string): Promise<Entry>;
export declare function chooseContentTypes(stack: any, displayMessage?: string): Promise<ContentType[]>;
export declare function chooseEnvironments(stack: any, displayMessage?: string): Promise<Environment[]>;
export declare function chooseEnvironment(stack: any, displayMessage?: string): Promise<Environment>;
export declare function chooseLocales(stack: any, displayMessage?: string): Promise<Locale[]>;
export declare function chooseLocale(stack: any, displayMessage?: string, defaultLocale?: Locale): Promise<Locale>;
export declare function chooseTokenAlias(): Promise<Token>;
export declare function chooseDeliveryTokenAlias(): Promise<Token>;
