export const ERROR_TYPES = {
  NETWORK: 'NETWORK_ERROR',
  DATABASE: 'DATABASE_ERROR',
  APPLICATION: 'APPLICATION_ERROR',
  UNKNOWN: 'UNKNOWN_ERROR',
  NORMALIZATION: 'NORMALIZATION_ERROR',
  API_RESPONSE: 'API_RESPONSE_DATA',
  API_ERROR: 'API_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
} as const;