module.exports = {
  assets: [
    {
      uid: 'dummyAssetId',
      created_at: '2019-11-04T08:40:41.341Z',
      updated_at: '2020-02-14T13:11:59.992Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/svg+xml',
      file_size: '2676',
      tags: [],
      filename: 'Content_manager.svg',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt42be7794369fbf06/5dbfe409a0b3fd4bbae67e30/Content_manager.svg',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      parent_uid: 'blt0829fdfd03dfabc5',
      _version: 2,
      title: 'Content_manager.svg',
      description: '',
    },
    {
      uid: 'dummyAssetId2',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
    {
      uid: 'dummyAssetId3',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
    {
      uid: 'dummyAssetId4',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
    {
      uid: 'dummyAssetId5',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
    {
      uid: 'dummyAssetId6',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
    {
      uid: 'dummyAssetId7',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
    {
      uid: 'dummyAssetId8',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
    {
      uid: 'dummyAssetId9',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
    {
      uid: 'dummyAssetId10',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
    {
      uid: 'dummyAssetId11',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
    {
      uid: 'dummyAssetId1s2',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
    {
      uid: 'dummyAssetId13',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
    {
      uid: 'dummyAssetId14',
      created_at: '2019-11-04T08:41:12.341Z',
      updated_at: '2019-11-04T08:41:12.341Z',
      created_by: '***REMOVED***',
      updated_by: '***REMOVED***',
      content_type: 'image/png',
      file_size: '344825',
      tags: [],
      filename: 'Snap.PNG',
      url: 'https://images.contentstack.io/v3/assets/***REMOVED***/blt0ebb164df30cd6d5/5dbfe4280eebac1e86b541b3/Snap.PNG',
      ACL: {
        roles: [],
        others: {
          read: false,
          create: false,
          update: false,
          delete: false,
          sub_acl: {
            read: false,
            create: false,
            update: false,
            delete: false,
            publish: false,
          },
        },
      },
      is_dir: false,
      _version: 1,
      title: 'Snap.PNG',
    },
  ],
  count: 14,
};
