name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.28.0
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r --sort --workspace-concurrency=1 run build
      - run: pnpm run lint
