name: CLI Release Pipeline

on:
  push:
    branches: [v1-beta]

jobs:
  plugins:
    uses: ./.github/workflows/release-v1-beta-platform-plugins.yml

  core:
    needs: plugins
    uses: ./.github/workflows/release-v1-beta-core.yml
