name: CLI v1-Legacy Release

on:
  push:
    branches: [v1-legacy]
  workflow_dispatch: # This enables manual triggering

jobs:
  plugins:
    uses: ./.github/workflows/release-v1-legacy-platform-plugins.yml
    secrets: inherit

  core:
    needs: plugins
    uses: ./.github/workflows/release-v1-legacy-core.yml
    secrets: inherit
