name: Source Composition Analysis Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # - uses: pnpm/action-setup@v2
      #   with:
      #     version: 7
      # - name: Use Node.js 16.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16.x'
      #     cache: 'pnpm'
      # - name: Install dependencies
      #   run: pnpm install --no-frozen-lockfile
      # - run: npx lerna bootstrap --force-local --concurrency 1
      - run: npm i --package-lock-only --workspaces
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects
