name: Secrets Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Gittyleaks
        uses: gupy-io/gittyleaks-action@v0.1