name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.28.0
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm -r --sort --workspace-concurrency=1 run build
      - name: Test contentstack
        working-directory: ./packages/contentstack
        run: pnpm test
      - name: Test contentstack-command
        working-directory: ./packages/contentstack-command
        run: pnpm test
      - name: Test contentstack-config
        working-directory: ./packages/contentstack-config
        run: pnpm test
      - name: Test contentstack-auth
        working-directory: ./packages/contentstack-auth
        run: pnpm test
      - name: Test contentstack-utilities
        working-directory: ./packages/contentstack-utilities
        run: pnpm test
